title: CV | My CV
description:  A beautiful template for your CV.
url: https://deadoralive1908.github.io/cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
